# SwiftLint Configuration File
# Based on TCA and other popular Swift projects

disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - large_tuple
  - unused_import
  - unused_declaration
  - unused_private_declaration

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

included:
  - Sources
  - Tests

excluded:
  - .build
  - .git
  - .swiftpm
  - Example
  - Documentation.docc

# Custom rules
custom_rules:
  no_print:
    name: "No Print"
    regex: 'print\('
    message: "Use proper logging instead of print statements"
    severity: warning

# Thresholds
function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

line_length:
  warning: 120
  error: 150

cyclomatic_complexity:
  warning: 10
  error: 20

# Reporter
reporter: "xcode"
