name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  XCODE_VERSION: "16.4"

jobs:
  test:
    name: Tests
    runs-on: macos-15

    strategy:
      matrix:
        include:
          - name: "macOS"
            destination: "platform=macOS"
          - name: "iOS"
            destination: "platform=iOS Simulator,name=iPhone 15,OS=latest"
          - name: "tvOS"
            destination: "platform=tvOS Simulator,name=Apple TV,OS=latest"
          - name: "watchOS"
            destination: "platform=watchOS Simulator,name=Apple Watch Series 9 (45mm),OS=latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Cache Swift packages
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            .build
          key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-

      - name: Build and test with xcodebuild
        run: |
          xcodebuild -resolvePackageDependencies
          xcodebuild -scheme swift-network -destination '${{ matrix.destination }}' build test
